# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [114]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))

    return matrix

def get_permutations(num_list):
    """
    num_list : tuple of integers,
        there aren't two same elements in the num_list.
    
    returns : list of tuples, all permutations of num_list
    """
    permutations = []
    
    if len(num_list) == 1:
        permutations.append(num_list)
        return permutations
    
    for i, ele in enumerate(num_list):
        num_list_without_ele = num_list[:i] + num_list[i+1:]
        permutations_without_ele = get_permutations(num_list_without_ele)
        
        for permutation in permutations_without_ele:
            permutations.append(tuple((ele,)) + tuple(permutation))
    
    return permutations

def multiple(permutation, matrix):
    """
    permutation : tuple, the permutation of (0, 1, 2, ..., n-1).
    matrix : matrix n×n, contains numbers.
    
    returns : number, the value of 
        matrix[0][permutation[0]] * matrix[1][permutation[1]] * ... * matrix[n-1][permutation[n-1]],
    """
    result = 1
    for i, index in enumerate(permutation):
        result *= matrix[i][index]
    
    return result

def inversion_count(permutation):
    """
    permutation : tuple, the permutation of (0, 1, 2, ..., n-1).
    
    returns : int, the count of inversions in the permutation.
    """
    n = len(permutation)
    inversions = 0
    
    for i in range(n):
        for j in range(i+1, n):
            if permutation[i] > permutation[j]:
                inversions += 1
    
    return inversions

def get_products(permutations, matrix):
    """
    permutations : list, contains all permutations of (0, 1, ..., n-1).
    matrix : matrix n×n, contains numbers.
    
    returns : list of two-element tuples, size : (count of permutations)×2,
        Each tuple contains:
        - a product of:
          matrix[0][a0], matrix[1][a1], ..., matrix[n-1][an-1]
          where (a0, a1, ..., an-1) - is permutation from permutations list;
        - and a count of inversions in (a0, a1, ..., an-1) permutation.
    """
    products = []
    
    for permutation in permutations:
        product = (multiple(permutation, matrix), inversion_count(permutation))
        products.append(product)
    
    return products

def sign(x):
    """
    x : int.
    
    returns : 1, if x is even,
        -1, if x is odd.
    """
    if x%2 == 0:
        return 1
    
    return -1

def sum_products(products):
    """
    products : list of two-element tuples, 
        Each tuple contains two numbers(the second one is 1 or -1)
    
    returns : number, the sum of products[i][0] * products[i][1]
    """
    result = 0
    
    for product, inv_count in products:
        result += product * sign(inv_count)
    
    return result


# main part:
n = None
try:
    n = int(input("Enter the dimension of square matrix: "))
    if n <= 0:
        raise ZeroDivisionError('n should be positive' + chr(128528))
except ZeroDivisionError as e:
    print(e)
except:
    print("Incorrect input" + chr(128579))
else:
    perm_0 = tuple([i for i in range(n)])
    permutations = get_permutations(perm_0)
    #np.random.seed(0)
    matrix = random_matrix(n)
    res = sum_products(get_products(permutations, matrix))
    
    #How to put previous lines in one line 
    #(in case if if I am only supposed to use function composition):
    #res = sum_products(get_products(get_permutations(tuple([i for i in range(n)])), random_matrix(n)))
    
    print(matrix)
    print(f"My result: {res}")
    print(f"Numpy result: {round(np.linalg.det(matrix), 3)}")

Enter the dimension of square matrix: 3
[[3 5 3]
 [2 4 4]
 [0 3 3]]
My result: -12
Numpy result: -12.0
